const assert = require('chai').assert;
const fs = require('fs');
const path = require('path');
const yaml = require('@gerhobbelt/js-yaml');
const JSON5 = require('@gerhobbelt/json5');
const globby = require('globby');
const helpers = require('../../helpers-lib/');
const rmCommonWS = helpers.rmCommonWS;

const json2jison = require('../json2jison');







console.log('exec glob....', __dirname);
const original_cwd = process.cwd();
process.chdir(__dirname);
let testset = globby.sync([
    './specs/*.json',
    './specs/*.json5',
]);
// also compile and run the JSON5 grammars in the /jison2json/tests/specs/**/reference-output/ directories:
let testset2 = globby.sync([
    '../../jison2json/tests/specs/**/reference-output/*.json5',
]);

testset = testset.sort();
testset2 = testset2.sort();
testset = testset.concat(testset2);     // append testset2 at the end of the list


const testsetSpec = helpers.setupFileBasedTestRig(__dirname, testset, 'json2jison', { useGeneratorRef: false });





describe('JSON2JISON', function () {

    beforeEach(function beforeEachTest() {
        // ...
    });

    testsetSpec.filespecList.forEach(function (filespec) {
        // process this file:
        let title = (filespec.meta ? filespec.meta.title : null);

        let testname = 'test: ' + filespec.filepath4display + (title ? ' :: ' + title : '');

        console.error('generate test: ', testname);

        // and create a test for it:
        it(testname, function testEachExample() {
            let json = filespec.grammar;
            let grammarspec = null;

            try {
                // Change CWD to the directory where the source grammar resides: this helps us properly
                // %include any files mentioned in the grammar with relative paths:
                process.chdir(path.dirname(filespec.path));

                grammarspec = json2jison.convert(json);
            } catch (ex) {
                grammarspec = {
                    fail: 1,
                    meta: filespec.spec.meta,
                    err: ex
                };
            } finally {
                process.chdir(original_cwd);
            }

            // either we check/test the correctness of the collected input, iff there's
            // a reference provided, OR we create the reference file for future use:
            let refOut = grammarspec;

            // strip away devbox-specific paths in error stack traces in the output:
            refOut = testsetSpec.stripErrorStackPaths(refOut);

            refOut = rmCommonWS`
                /* 
                 * grammar spec generated by @gerhobbelt/json2jison for input file:
                 *     ${filespec.filepath4display}
                 */

            `.trimStart() + refOut;

            if (filespec.ref) {
                // Perform the validations only AFTER we've written the files to output:
                // several tests produce very large outputs, which we shouldn't let assert() process
                // for diff reporting as that takes bloody ages:
            } else {
                fs.writeFileSync(filespec.outputRefPath, refOut, 'utf8');
                filespec.ref = refOut;
            }
            fs.writeFileSync(filespec.outputOutPath, refOut, 'utf8');

            // now that we have saved all data, perform the validation checks:
            // keep them simple so assert doesn't need a lot of time to produce diff reports
            // when the test fails:
            testsetSpec.assertOutputMatchesReference(refOut, filespec.ref, 'generated grammar spec does not match reference; please compare /output/ vs /reference-output/');
        });
    });
});

